### ISSUE TITLE
[cluster] CVE-2019-5736 fix

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#6682]
This would also have prevented https://github.com/hail-is/hail/issues/6679

Fix is:

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: non-root
spec:
  privileged: false
  allowPrivilegeEscalation: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
```
